
const NF_HOST_REMOTE_ENTRY = "__NF-HOST__";

const NF_STORAGE_ENTRY = "__NATIVE-FEDERATION__";

const NF_REMOTE_ENTRY_FILENAME = "remoteEntry.json";

export { NF_HOST_REMOTE_ENTRY, NF_STORAGE_ENTRY, NF_REMOTE_ENTRY_FILENAME }
